config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#home'
  get 'docs', to: 'pages#docs', as: :docs
  resources :api_keys, only: [:index, :create]
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # confirmable
  get 'confirm/*token', to: 'users#confirm', as: :confirm_email, constraints: { token: /.*/ }
  # resettable
  get 'reset_password', to: 'users#reset_password_request_form', as: :reset_password_request_form
  post 'reset_password_request', to: 'users#reset_password_request', as: :reset_password_request
  get 'reset_password/*token', to: 'users#reset_password_form', as: :reset_password_form, constraints: { token: /.*/ }
  post 'reset_password/*token', to: 'users#reset_password', as: :reset_password, constraints: { token: /.*/ }

  namespace :api do
    post :geolocation, controller: :ip_addresses, action: :geolocation
  end
end

app/views/partials/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/partials/_header.html.erb
<div class='header-container pb50'>
  <div class='header-inner-container'>
    <div class='logo'>
      <a href=<%= url_for root_path %>><i class='fa fa-globe header-logo' id='header-logo' aria-hidden='true'></i></a>
      <%= link_to 'Free IP Geolocation', root_path, class: 'header-logo' %>
    </div>
    <div class='pages-links'>
      <%= link_to 'Docs', docs_path, class: 'header-link' %>
      <% if logged_in? %>
        <%= link_to 'Api Keys', api_keys_path, method: :get, class: 'header-link' %>
        <%= link_to 'Sign Out', session_path, method: :delete, class: 'header-link' %>
      <% else %>
        <%= link_to 'Sign In', login_path, class: 'header-link' %>
        <%= link_to 'Register', new_user_path, class: 'header-link' %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_request_geolocation.html.erb
<div class='column-container'>
  <div class='column-container geolocation code-block p10'>
    <div id='request-ip'><p class='fa fa-map-marker'><%= @request_ip %></p></div>
    <p>country: <%= @location&.country %>,</p>
    <p>abbreviation: <%= @location&.abbreviation %>,</p>
    <p>region: <%= @location&.region %>,</p>
    <p>city: <%= @location&.city %></p>
  </div>
</div>